{% set name = "weldx" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 191fdeea0b249dcd4adb9360f6422c10fa9cbb7034161431df96c98cede81dbd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools_scm
    - python
  run:
    - python >=3.8
    - numpy >=1.20
    - asdf >=2.8.2,!=2.14.0,!=2.14.1,!=2.14.2
    - pandas >=1.0
    - xarray >=0.19,<2022.09.0
    - scipy >=1.4,!=1.6.0,!=1.6.1
    - sympy >=1.6
    - pint >=0.18
    - pint-xarray >=0.2.1
    - bottleneck >=1.3.3
    - boltons
    - bidict
    - networkx >=2,!=2.7.0,!=2.8.1
    - fs
    - meshio
    - psutil
    - IPython
test:
  requires:
    - pip
  imports:
    - weldx
    - weldx.visualization
  commands:
    - pip check
    - welding_schema --help

about:
  home: https://www.bam.de/Content/EN/Projects/WelDX/weldx.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python API for the WelDX file format and standard
  description: |
    Scientific welding data covers a wide range of physical domains and
    timescales and are measured using various different sensors. Complex and
    highly specialized experimental setups at different welding institutes
    complicate the exchange of welding research data further.

    The WelDX research project aims to foster the exchange of scientific data
    inside the welding community by developing and establishing a new open
    source file format suitable for documentation of experimental welding data
    and upholding associated quality standards. In addition to fostering
    scientific collaboration inside the national and international welding
    community an associated advisory committee will be established to oversee
    the future development of the file format. The proposed file format will be
    developed with regard to current needs of the community regarding
    interoperability, data quality and performance and will be published under
    an appropriate open source license. By using the file format objectivity,
    comparability and reproducibility across different experimental setups can
    be improved.
  doc_url: https://weldx.readthedocs.io
  dev_url: https://github.com/BAMWelDX/weldx/

extra:
  recipe-maintainers:
    - marscher
    - vhirtham
    - CagtayFabry
